import {Component,inject} from '@angular/core';
import {bootstrapApplication} from '@angular/platform-browser';
import {provideHttpClient,HttpClient} from '@angular/common/http';
import {FormsModule} from '@angular/forms';
import {CommonModule} from '@angular/common';
interface Cert {id:number;applicationName:string;environment:string;expiryDate:string;ownerTeam:string;recipients:string[];daysRemaining:number;status:string;}
@Component({selector:'app-root',standalone:true,imports:[FormsModule,CommonModule],template:`
<header><div class="brand">◈ <span>Neshtek <small>OPERATIONS</small></span></div><span class="pill">Certificate monitoring</span></header>
<main><div class="heading"><div><div class="eyebrow">APPLICATION HEALTH</div><h1>Certificate expiry dashboard</h1><p>Keep renewals visible. Keep your applications running.</p></div><button (click)="tab=1">+ Add application</button></div>
<section class="stats"><article><span>Applications</span><strong>{{certs.length}}</strong><small>Across all environments</small></article><article><span>Critical</span><strong class="red">{{critical}}</strong><small>Expires within 30 days or expired</small></article><article><span>Safe</span><strong class="green">{{certs.length-critical}}</strong><small>More than 30 days remaining</small></article></section>
<nav aria-label="Dashboard tabs"><button *ngFor="let name of tabs; let i=index" [class.active]="tab===i" (click)="tab=i">{{name}}</button></nav>
<div role="status" class="notice" *ngIf="message">{{message}}</div>
<section class="panel" *ngIf="tab===0"><div class="toolbar"><div><h2>Application certificates</h2><p>Prioritised by expiry date</p></div><input aria-label="Search applications" placeholder="Search application or owner…" [(ngModel)]="search"><select aria-label="Filter environment" [(ngModel)]="filter"><option value="">All environments</option><option *ngFor="let env of environments">{{env}}</option></select><button class="secondary" (click)="load()" [disabled]="loading">{{loading?'Loading…':'Refresh'}}</button></div><div class="table-scroll"><table><thead><tr><th>Application name</th><th>Environment name</th><th>Expiry date</th><th>Status</th><th>Application owner name</th></tr></thead><tbody><tr *ngFor="let c of filtered"><td><b>{{c.applicationName}}</b></td><td><span class="env">{{c.environment}}</span></td><td>{{c.expiryDate | date:'dd MMM yyyy'}}<small>{{c.daysRemaining < 0 ? 'Expired '+(-c.daysRemaining)+' days ago' : c.daysRemaining+' days remaining'}}</small></td><td><span class="badge" [class.critical]="c.status==='Critical'">{{c.status}}</span></td><td>{{c.ownerTeam}}</td></tr><tr *ngIf="!filtered.length"><td colspan="5" class="empty">{{loading?'Loading certificates…':'No certificates found. Add your first application.'}}</td></tr></tbody></table></div><footer>Daily reminders for critical certificates • 09:00 India time by default</footer></section>
<section class="panel form-panel" *ngIf="tab===1"><h2>Add application</h2><p>Register a certificate and the team responsible for renewal.</p><form #addForm="ngForm" (ngSubmit)="add()"><div class="grid"><label>Application name<input name="applicationName" required maxlength="200" [(ngModel)]="application.applicationName" placeholder="e.g. WebCenter Content"></label><label>Application environment<select name="environment" [(ngModel)]="application.environment" required><option *ngFor="let env of environments">{{env}}</option></select></label><label>Expiry date<input type="date" name="expiryDate" required [(ngModel)]="application.expiryDate"></label><label>Application owner team name<input name="ownerTeam" required maxlength="200" [(ngModel)]="application.ownerTeam" placeholder="e.g. ECM Operations"></label></div><label>Recipient email list<textarea name="recipients" required [(ngModel)]="recipientsText" placeholder="owner@example.com, support@example.com"></textarea><small>Separate email addresses with commas, semicolons or new lines. Each recipient receives a daily alert within 30 days of expiry.</small></label><div class="actions"><button type="submit" [disabled]="addForm.invalid || saving">{{saving?'Saving…':'Save application'}}</button><button type="button" class="secondary" (click)="tab=0">Cancel</button></div></form></section>
<section class="panel form-panel" *ngIf="tab===2"><h2>Email configuration</h2><p>Configure the SMTP provider used to send certificate alerts.</p><form #mailForm="ngForm" (ngSubmit)="saveMail()"><div class="grid"><label>Email provider<input name="provider" required [(ngModel)]="mail.provider" placeholder="e.g. Company SMTP"></label><label>SMTP host<input name="host" required [(ngModel)]="mail.host" placeholder="smtp.example.com"></label><label>SMTP port<input name="port" type="number" min="1" max="65535" required [(ngModel)]="mail.port"></label><label>Security<select name="security" [(ngModel)]="mail.security"><option>STARTTLS</option><option>SSL</option></select></label><label>SMTP username<input name="username" [(ngModel)]="mail.username"></label><label>Sender email<input name="fromEmail" type="email" email required [(ngModel)]="mail.fromEmail"></label></div><div class="help">Set the SMTP password in the backend's <code>SMTP_PASSWORD</code> environment variable and restart it. It is never stored in the browser or returned by the API. Your provider must permit SMTP authentication or an approved SMTP relay.</div><label class="check"><input type="checkbox" name="enabled" [(ngModel)]="mail.enabled"> Enable daily certificate alerts</label><button [disabled]="mailForm.invalid || saving">{{saving?'Saving…':'Save email configuration'}}</button></form></section></main>`})
class App {
 private http=inject(HttpClient); tabs=['Application certs','Add Application','Email configuration'];environments=['PROD','DR','TEST','DEV','UAT'];tab=0;certs:Cert[]=[];search='';filter='';message='';loading=false;saving=false;recipientsText='';
 application={applicationName:'',environment:'PROD',expiryDate:'',ownerTeam:''};mail={provider:'',host:'',port:587,username:'',fromEmail:'',security:'STARTTLS',enabled:false};
 constructor(){this.load();this.http.get<typeof this.mail|null>('/api/email-config').subscribe({next:c=>{if(c)this.mail=c;},error:()=>{this.message='Cannot load email configuration. Check the backend connection.';}});}
 get critical(){return this.certs.filter(c=>c.status==='Critical').length;}
 get filtered(){let q=this.search.toLowerCase();return this.certs.filter(c=>(!this.filter||c.environment===this.filter)&&(c.applicationName.toLowerCase().includes(q)||c.ownerTeam.toLowerCase().includes(q)));}
 load(){this.loading=true;this.http.get<Cert[]>('/api/certificates').subscribe({next:c=>{this.certs=c;this.loading=false;},error:e=>{this.loading=false;this.fail(e);}});}
 fail(e:any){this.saving=false;this.message=e.error?.message||'Request failed. Check that the backend is running and Oracle is configured.';}
 add(){let recipients=[...new Set(this.recipientsText.split(/[,;\n]+/).map(x=>x.trim()).filter(Boolean))];if(!recipients.length||recipients.some(x=>!/^\S+@\S+\.\S+$/.test(x))){this.message='Enter valid recipient email addresses.';return;}this.saving=true;this.http.post('/api/certificates',{...this.application,recipients}).subscribe({next:()=>{this.saving=false;this.message='Application added successfully.';this.application={applicationName:'',environment:'PROD',expiryDate:'',ownerTeam:''};this.recipientsText='';this.tab=0;this.load();},error:e=>this.fail(e)});}
 saveMail(){this.saving=true;this.http.put('/api/email-config',this.mail).subscribe({next:()=>{this.saving=false;this.message='Email configuration saved.';},error:e=>this.fail(e)});}
}
bootstrapApplication(App,{providers:[provideHttpClient()]}).catch(console.error);
